# 作業 : (Kaggle)鐵達尼生存預測

# [作業目標]
- 試著完成三種不同特徵類型的三種資料操作, 觀察結果
- 思考一下, 這三種特徵類型, 哪一種應該最複雜/最難處理

# [作業重點]
- 完成剩餘的八種 類型 x 操作組合 (In[6]~In[13], Out[6]~Out[13])
- 思考何種特徵類型, 應該最複雜

In [5]:
# 載入基本套件
import pandas as pd
import numpy as np

# 讀取訓練與測試資料
data_path = 'data/'
df_train = pd.read_csv(data_path + 'titanic_train.csv')
df_test = pd.read_csv(data_path + 'titanic_test.csv')
df_train.shape

(891, 12)

In [6]:
# 重組資料成為訓練 / 預測用格式
train_Y = df_train['Survived']
ids = df_test['PassengerId']
df_train = df_train.drop(['PassengerId', 'Survived'] , axis=1)
df_test = df_test.drop(['PassengerId'] , axis=1)
df = pd.concat([df_train,df_test])
df.head()
df.shape

(1309, 10)

In [11]:
# 秀出資料欄位的類型與數量
dtype_df = df.dtypes.reset_index()
dtype_df.columns = ["Count", "Column Type"]
dtype_df = dtype_df.groupby("Column Type").aggregate('count').reset_index()
dtype_df
#另一種方法
df.dtypes.value_counts()

object     5
int64      3
float64    2
dtype: int64

In [12]:
#確定只有 int64, float64, object 三種類型後, 分別將欄位名稱存於三個 list 中
int_features = []
float_features = []
object_features = []
for dtype, feature in zip(df.dtypes, df.columns):
    if dtype == 'float64':
        float_features.append(feature)
    elif dtype == 'int64':
        int_features.append(feature)
    else:
        object_features.append(feature)
print(f'{len(int_features)} Integer Features : {int_features}\n')
print(f'{len(float_features)} Float Features : {float_features}\n')
print(f'{len(object_features)} Object Features : {object_features}')

3 Integer Features : ['Pclass', 'SibSp', 'Parch']

2 Float Features : ['Age', 'Fare']

5 Object Features : ['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']


# 作業1 
* 試著執行作業程式，觀察三種類型 (int / float / object) 的欄位分別進行( 平均 mean / 最大值 Max / 相異值 nunique )  
中的九次操作會有那些問題? 並試著解釋那些發生Error的程式區塊的原因? 
ans:Object,字串類型不能比大小也無平均值概念

# 作業2
* 思考一下，試著舉出今天五種類型以外的一種或多種資料類型，你舉出的新類型是否可以歸在三大類中的某些大類?  
所以三大類特徵中，哪一大類處理起來應該最複雜?
ans:相似度,可能可以歸在類別,時間類型最複雜

In [29]:
# 請依序列出 三種特徵類型 (int / float / object) x 三種方法 (平均 mean / 最大值 Max / 相異值 nunique) 的其餘操作
# 例 : 整數 (int) 特徵取平均 (mean)
print(df[int_features].mean())
print(df[int_features].max())
print(df[int_features].nunique())
#印出int_feature各欄位的類別
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for col in int_features:
    le.fit(df[col])
    print(le.classes_)

Pclass    2.294882
SibSp     0.498854
Parch     0.385027
dtype: float64
Pclass    3
SibSp     8
Parch     9
dtype: int64
Pclass    3
SibSp     7
Parch     8
dtype: int64
[1 2 3]
[0 1 2 3 4 5 8]
[0 1 2 3 4 5 6 9]


In [36]:
#float
print(df[float_features].mean())
print(df[float_features].max())
print(df[float_features].nunique())
#印出float_feature各欄位的類別
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for col in float_features:
    le.fit(df[col])
    print(le.classes_)


Age     29.881138
Fare    33.295479
dtype: float64
Age      80.0000
Fare    512.3292
dtype: float64
Age      98
Fare    281
dtype: int64
[ 0.17  0.33  0.42  0.67  0.75  0.83  0.92  1.    2.    3.    4.    5.
  6.    7.    8.    9.   10.   11.   11.5  12.   13.   14.   14.5  15.
 16.   17.   18.   18.5  19.   20.   20.5  21.   22.   22.5  23.   23.5
 24.   24.5  25.   26.   26.5  27.   28.   28.5  29.   30.   30.5  31.
 32.   32.5  33.   34.   34.5  35.   36.   36.5  37.   38.   38.5  39.
 40.   40.5  41.   42.   43.   44.   45.   45.5  46.   47.   48.   49.
 50.   51.   52.   53.   54.   55.   55.5  56.   57.   58.   59.   60.
 60.5  61.   62.   63.   64.   65.   66.   67.   70.   70.5  71.   74.
 76.   80.     nan   nan   nan   nan   nan   nan   nan   nan   nan   nan
   nan   nan   nan   nan   nan   nan   nan   nan   nan   nan   nan   nan
   nan   nan   nan   nan   nan   nan   nan   nan   nan   nan   nan   nan
   nan   nan   nan   nan   nan   nan   nan   nan   nan   nan   nan   nan
  

In [ ]:
'Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'

In [46]:
#object
print(df[object_features].mean())
print(df[object_features].max())
print(df[object_features].nunique())
#印出object_feature各欄位的類別,Cabin,Embarked無法使用labelcoder
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for col in object_features:
    le.fit(df[col])
    print(le.classes_)

Series([], dtype: float64)
Name      van Melkebeke, Mr. Philemon
Sex                              male
Ticket                      WE/P 5735
dtype: object
Name        1307
Sex            2
Ticket       929
Cabin        186
Embarked       3
dtype: int64
['Abbing, Mr. Anthony' 'Abbott, Master. Eugene Joseph'
 'Abbott, Mr. Rossmore Edward' ... 'van Billiard, Master. Walter John'
 'van Billiard, Mr. Austin Blyler' 'van Melkebeke, Mr. Philemon']
['female' 'male']
['110152' '110413' '110465' '110469' '110489' '110564' '110813' '111163'
 '111240' '111320' '111361' '111369' '111426' '111427' '111428' '112050'
 '112051' '112052' '112053' '112058' '112059' '112277' '112377' '112378'
 '112379' '112901' '113028' '113038' '113043' '113044' '113050' '113051'
 '113054' '113055' '113056' '113059' '113501' '113503' '113505' '113509'
 '113510' '113514' '113572' '113760' '113767' '113773' '113776' '113778'
 '113780' '113781' '113783' '113784' '113786' '113787' '113788' '113789'
 '113790' '113791' '113792

TypeError: '<' not supported between instances of 'str' and 'float'